### ISSUE TITLE
Cannot resize boxes

### ISSUE THREAD

**Issue by Anabad** [antingshen/BeaverDam#135]
Once I've drawn a box, I can neither resize it nor make a new box. Do you know why this might be happening?

If it helps, I am getting the following error when the page loads.

`Internal Server Error: /get_states/
Traceback (most recent call last):
  File "/home/anand/workspace/BeaverDam/venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/home/anand/workspace/BeaverDam/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/home/anand/workspace/BeaverDam/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/anand/workspace/BeaverDam/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/anand/workspace/BeaverDam/annotator/views.py", line 178, in get_states
    states = State.objects.filter(label_name=label_name)
UnboundLocalError: local variable 'label_name' referenced before assignment
[25/Jan/2018 08:54:10] "GET /annotation/2/ HTTP/1.1" 200 0
[25/Jan/2018 08:54:10] "GET /get_states/?label_name= HTTP/1.1" 500 79341
`

**Comment by antingshen** [comment]
Hmm seems like a new bug. @jeanineharb 

Try reverting to commit ca283928aa523188acd5c743c4ab53e9c1a4eb1b

**Comment by jeanineharb** [comment]
Are your dropdown lists for labels and states populated with data?
This error seems to be caused by an empty selection for the annotation label.

**Comment by Anabad** [comment]
You're correct they're not populated, how can I do that?

**Comment by Anabad** [comment]
Nevermind, I figured it out, thanks for your help.

**Comment by exoticmoose** [comment]
@Anabad What did you end up doing?

**Comment by antingshen** [comment]
Populate the labels & states with data, I'm guessing. 

Try going to /admin and adding labels & states there. Even if just a single label with a single state (they can be empty).

**Comment by clayshieh** [comment]
~~might still be a bug with the commit. would need to check if there is a default value added for the model field so that south properly generates a non breaking migration for existing BeaverDam instances.~~

error was in python backend, fixed in pr

**Comment by exoticmoose** [comment]
Yup! Turned out to just be that the data label and states were unpopulated.

Fixed under /admin control panel as antingshen mentioned.
