### ISSUE TITLE
Broken Install

### ISSUE THREAD

**Issue by MatthewMcLeod** [antingshen/BeaverDam#161]
I am installing on a Unbuntu 16.04 system and the adding data script is failing. Running scripts/setup works fine but scripts/seed -f gives an error. The following is the error in console.

$ wget https://s3-us-west-2.amazonaws.com/beaverdam/db.sqlite3 -O db.sqlite3
--2019-06-03 14:37:14--  https://s3-us-west-2.amazonaws.com/beaverdam/db.sqlite3
Resolving s3-us-west-2.amazonaws.com (s3-us-west-2.amazonaws.com)... 52.218.160.76
Connecting to s3-us-west-2.amazonaws.com (s3-us-west-2.amazonaws.com)|52.218.160.76|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 119808 (117K) [application/octet-stream]
Saving to: ‘db.sqlite3’

db.sqlite3          100%[===================>] 117.00K   413KB/s    in 0.3s    

2019-06-03 14:37:15 (413 KB/s) - ‘db.sqlite3’ saved [119808/119808]

$ wget https://s3-us-west-2.amazonaws.com/beaverdam/videos/test_vid2.mp4 -O annotator/static/videos/0.mp4
--2019-06-03 14:37:15--  https://s3-us-west-2.amazonaws.com/beaverdam/videos/test_vid2.mp4
Resolving s3-us-west-2.amazonaws.com (s3-us-west-2.amazonaws.com)... 52.218.160.76
Connecting to s3-us-west-2.amazonaws.com (s3-us-west-2.amazonaws.com)|52.218.160.76|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2063958 (2.0M) [application/octet-stream]
Saving to: ‘annotator/static/videos/0.mp4’

annotator/static/vi 100%[===================>]   1.97M   880KB/s    in 2.3s    

2019-06-03 14:37:18 (880 KB/s) - ‘annotator/static/videos/0.mp4’ saved [2063958/2063958]

Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 363, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 337, in execute
    django.setup()
  File "/usr/local/lib/python2.7/dist-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python2.7/dist-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models()
  File "/usr/local/lib/python2.7/dist-packages/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/jzelek/Desktop/AnnotationTools/BeaverDam/annotator/models.py", line 49
    def from_list(cls, path_to_list, *, source, host, filename_prefix=''):
                                      ^
SyntaxError: invalid syntax

When I try to continue on with scripts/serve, the localhost opens with the following error
![beaverdam](https://user-images.githubusercontent.com/8856013/58826079-de131480-860d-11e9-9bc5-435f122e491f.png)

The software versions are:

Python: 3.5.2
VirtualEnv:  16.4.1

**Comment by antingshen** [comment]
Looks like you're installing with python 2 instead of python 3 somehow

**Comment by MatthewMcLeod** [comment]
Any idea how to get the install script to call python 3 instead of python 2?

**Comment by clayshieh** [comment]
The seed script assumes that you run it right after the setup script. You have two options:
1. run the setup script before you run the seed script
2. execute `source venv/bin/activate` before running the seed script
