### ISSUE TITLE
Frame Stepping is broken (?)

### ISSUE THREAD

**Issue by CarlosUvaSilva** [antingshen/BeaverDam#162]
I'm trying to annotate a video but each time I hit either "a" or "s" to go forward or backwards frame-by-frame the timeline just resets to 0.

am I doing anything wrong or is this a bug?

Running latest version in Linux Mint 19.2

I'm getting this in the beaverdam console logs if it helps 

```
Traceback (most recent call last):
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 141, in run
    self.handle_error()
  File "/home/carlos/code/utils/BeaverDam/venv/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 95, in handle_error
    super(ServerHandler, self).handle_error()
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 368, in handle_error
    self.finish_response()
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 180, in finish_response
    self.write(data)
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 274, in write
    self.send_headers()
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 331, in send_headers
    if not self.origin_server or self.client_is_modern():
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 344, in client_is_modern
    return self.environ['SERVER_PROTOCOL'].upper() != 'HTTP/0.9'
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/home/carlos/code/utils/BeaverDam/venv/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 174, in handle
    handler.run(self.server.get_app())
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 144, in run
    self.close()
  File "/usr/lib/python3.6/wsgiref/simple_server.py", line 35, in close
    self.status.split(' ',1)[0], self.bytes_sent
AttributeError: 'NoneType' object has no attribute 'split'
```

**Comment by clayshieh** [comment]
Frame stepping shouldn't be sending any requests back to the server. Could you open up developer tools in your browser and post what network requests are being sent to the backend when you press a or s?

Also try running in incognito mode with all extensions disabled to make sure theres no other extensions or plugins that are using the a and s keys.

**Comment by CarlosUvaSilva** [comment]
hello @clayshieh 

this is the network requests from an incognito window. I still can't step frame by frame, it still jumps to the beginning
![image](https://user-images.githubusercontent.com/6827956/63678025-352c1e00-c7e6-11e9-8d96-e2886d6ebd33.png)

**Comment by CarlosUvaSilva** [comment]
@clayshieh sorry to bother you again but do you have any idea why this might  be happening?
it's impossible to accurately annotate a video without frame stepping :cry:
